# Generated by Django 4.0.4 on 2022-06-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_games_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='typea',
            field=models.CharField(max_length=111111111),
        ),
    ]
